name: Issue Bot

on:
  issues:
    types: [opened, edited]

jobs:
  deploy:
    if: contains(github.event.issue.body || '', '?startdns')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy something
        run: |
          echo "🚀 Starting DNS deployment..."
          # not done

      - name: Comment on the issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              body: "✅ DNS deployment started successfully! Closing this issue."
            })

      - name: Close the issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              state: "closed"
            })
